import { QTableColumn } from 'quasar';
import { TestClientInterface } from '../Models/TestClient';

const clientColumns: QTableColumn<TestClientInterface & { checkDeploy: unknown; delete: unknown; rowIndex: number }>[] = [
  {
    name: 'no',
    required: false,
    label: 'No',
    align: 'left',
    field: 'rowIndex',
    sortable: true,
    style: 'max-width: 30px; text-align: center;',
    headerStyle: 'max-width: 30px',
  },
  {
    name: 'id',
    required: false,
    label: 'Id',
    align: 'left',
    field: (row) => row.Id,
    format: (val) => `${val}`,
    sortable: false,
  },
  {
    name: 'name',
    required: false,
    label: 'Name',
    align: 'left',
    field: 'Name',
    format: (val) => `${val}`,
    sortable: true,
  },

  {
    name: 'ipAddress',
    required: true,
    label: 'IP Address',
    align: 'left',
    field: 'IPAddress',
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: 'type',
    required: false,
    label: 'Type',
    align: 'left',
    field: 'Type',
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: 'user',
    required: false,
    label: 'User',
    align: 'left',
    field: 'User',
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: 'password',
    required: false,
    label: 'Password',
    align: 'left',
    field: 'Password',
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: 'regressionFolder',
    required: false,
    label: 'Regression Folder',
    align: 'left',
    field: 'RegressionFolder',
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: 'developFolder',
    required: false,
    label: 'Develop Folder',
    align: 'left',
    field: 'DevelopFolder',
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: 'runnerFolder',
    required: false,
    label: 'Runner Folder',
    align: 'left',
    field: 'RunnerFolder',
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: 'Status',
    required: false,
    label: 'Status',
    align: 'left',
    field: 'Status',
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: 'description',
    required: false,
    label: 'Description',
    align: 'left',
    field: 'Description',
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: 'delete',
    align: 'left',
    label: 'Delete',
    field: 'delete',
    sortable: false,
  },
  {
    name: 'checkDeploy',
    align: 'left',
    label: 'Check Deploy',
    field: 'checkDeploy',
    sortable: false,
  },
];
const testEnvColumns = [
  {
    name: 'no',
    required: true,
    label: 'No',
    align: 'left',
    field: 'rowIndex',
    sortable: true,
    style: 'max-width: 30px; text-align: center;',
    headerStyle: 'max-width: 30px',
  },
  {
    name: 'category',
    required: true,
    label: 'Category',
    align: 'left',
    field: 'Category',
    format: (val) => `${val}`,
    sortable: true,
  },
  {
    name: 'name',
    align: 'left',
    label: 'Name',
    field: 'Name',
    sortable: true,
    style: 'min-width: 100px',
    headerStyle: 'min-width: 100px',
  },
  {
    name: 'value',
    align: 'left',
    label: 'Value',
    field: 'Value',
    style: 'max-width: 100px',
    headerStyle: 'max-width: 100px',
    sortable: true,
    classes: 'ellipsis',
  },
  {
    name: 'description',
    align: 'left',
    label: 'Description',
    field: 'Description',
    sortable: true,
  },
  {
    name: 'use',
    align: 'left',
    label: '',
    field: 'use',
    sortable: false,
  },
  {
    name: 'delete',
    align: 'left',
    label: '',
    field: 'use',
    sortable: false,
  },
];
const testCaseColumns = [
  {
    name: 'no',
    required: true,
    label: 'No',
    align: 'left',
    // eslint-disable-next-line @typescript-eslint/no-unsafe-return
    field: 'rowIndex',
    sortable: false,
    style: 'max-width: 40px',
    headerStyle: 'max-width: 40px',
  },
  {
    name: 'testAUT',
    align: 'center',
    label: 'TestAUT',
    field: 'TestAUT',
    sortable: false,
    style: 'min-width: 80px; max-width: 100px',
    headerStyle: 'min-width: 80px; max-width: 100px',
  },
  {
    name: 'keyword',
    label: 'Keyword',
    field: 'Keyword',
    sortable: false,
    align: 'left',
    style: 'min-width: 150px;',
    headerStyle: 'min-width: 150px',
  },
  {
    name: 'param1',
    label: 'Param 1',
    field: 'Param1',
    sortable: false,
    align: 'left',
    style: 'min-width: 135px;',
    headerStyle: 'min-width: 135px',
  },
  {
    name: 'param2',
    label: 'Param 2',
    field: 'Param2',
    sortable: false,
    align: 'left',
    style: 'min-width: 135px;',
    headerStyle: 'min-width: 135px',
  },
  {
    name: 'param3',
    label: 'Param 3',
    field: 'Param3',
    sortable: false,
    align: 'left',
    style: 'min-width: 135px;',
    headerStyle: 'min-width: 135px',
  },
  {
    name: 'param4',
    label: 'Param 4',
    field: 'Param4',
    sortable: false,
    align: 'left',
    style: 'min-width: 135px;',
    headerStyle: 'min-width: 135px',
  },
  {
    name: 'param5',
    label: 'Param 5',
    field: 'Param5',
    sortable: false,
    align: 'left',
    style: 'min-width: 135px;',
    headerStyle: 'min-width: 135px',
  },
  {
    name: 'param6',
    label: 'Param 6',
    field: 'Param6',
    sortable: false,
    align: 'left',
    style: 'min-width: 135px;',
    headerStyle: 'min-width: 135px',
  },
  {
    name: 'param7',
    label: 'Param 7',
    field: 'Param7',
    sortable: false,
    align: 'left',
    style: 'min-width: 135px;',
    headerStyle: 'min-width: 135px',
  },
  {
    name: 'param8',
    label: 'Param 8',
    field: 'Param8',
    sortable: false,
    align: 'left',
    style: 'min-width: 135px;',
    headerStyle: 'min-width: 135px',
  },
  {
    name: 'param9',
    label: 'Param 9',
    field: 'Param9',
    sortable: false,
    align: 'left',
    style: 'min-width: 135px;',
    headerStyle: 'min-width: 135px',
  },
  {
    name: 'param10',
    label: 'Param 10',
    field: 'Param10',
    sortable: false,
    align: 'left',
    style: 'min-width: 135px;',
    headerStyle: 'min-width: 135px',
  },
  {
    name: 'param11',
    label: 'Param 11',
    field: 'Param11',
    sortable: false,
    align: 'left',
    style: 'min-width: 135px;',
    headerStyle: 'min-width: 135px',
  },
  {
    name: 'param12',
    label: 'Param 12',
    field: 'Param12',
    sortable: false,
    align: 'left',
    style: 'min-width: 135px;',
    headerStyle: 'min-width: 135px',
  },
  {
    name: 'param13',
    label: 'Param 13',
    field: 'Param13',
    sortable: false,
    align: 'left',
    style: 'min-width: 135px;',
    headerStyle: 'min-width: 135px',
  },
  {
    name: 'param14',
    label: 'Param 14',
    field: 'Param14',
    sortable: false,
    align: 'left',
    style: 'min-width: 135px;',
    headerStyle: 'min-width: 135px',
  },
  {
    name: 'param15',
    label: 'Param 15',
    field: 'Param15',
    sortable: false,
    align: 'left',
    style: 'min-width: 135px;',
    headerStyle: 'min-width: 135px',
  },
  {
    name: 'param16',
    label: 'Param 16',
    field: 'Param16',
    sortable: false,
    align: 'left',
    style: 'min-width: 135px;',
    headerStyle: 'min-width: 135px',
  },
  {
    name: 'param17',
    label: 'Param 17',
    field: 'Param17',
    sortable: false,
    align: 'left',
    style: 'min-width: 135px;',
    headerStyle: 'min-width: 135px',
  },
  {
    name: 'param18',
    label: 'Param 18',
    field: 'Param18',
    sortable: false,
    align: 'left',
    style: 'min-width: 135px;',
    headerStyle: 'min-width: 135px',
  },
  {
    name: 'param19',
    label: 'Param 19',
    field: 'Param19',
    sortable: false,
    align: 'left',
    style: 'min-width: 135px;',
    headerStyle: 'min-width: 135px',
  },
  {
    name: 'param20',
    label: 'Param 20',
    field: 'Param20',
    sortable: false,
    align: 'left',
    style: 'min-width: 135px;',
    headerStyle: 'min-width: 135px',
  },
];
export { clientColumns, testEnvColumns, testCaseColumns };
