const clientColumns = [
  {
    name: 'Id',
    required: false,
    label: 'Id',
    align: 'left',
    // eslint-disable-next-line @typescript-eslint/no-unsafe-return
    field: (row: any) => row.Id,
    format: (val: any) => `${val}`,
    sortable: false,
  },
  {
    name: 'Name',
    required: false,
    label: 'Name',
    align: 'left',
    field: 'Name',
    format: (val: any) => `${val}`,
    sortable: true,
  },
  {
    name: 'Description',
    required: false,
    label: 'Description',
    align: 'left',
    field: 'Description',
    format: (val: any) => `${val}`,
    sortable: true,
  },
  {
    name: 'IPAddress',
    required: true,
    label: 'IP Address',
    align: 'left',
    field: 'IPAddress',
    format: (val: any) => `${val}`,
    sortable: true,
  },
  {
    name: 'Type',
    required: false,
    label: 'Type',
    align: 'left',
    field: 'Type',
    format: (val: any) => `${val}`,
    sortable: true,
  },
  {
    name: 'User',
    required: false,
    label: 'User',
    align: 'left',
    field: 'User',
    format: (val: any) => `${val}`,
    sortable: true,
  },
  {
    name: 'Password',
    required: false,
    label: 'Password',
    align: 'left',
    field: 'Password',
    format: (val: any) => `${val}`,
    sortable: true,
  },
  {
    name: 'RegressionFolder',
    required: false,
    label: 'Regression Folder',
    align: 'left',
    field: 'RegressionFolder',
    format: (val: any) => `${val}`,
    sortable: true,
  },
  {
    name: 'DevelopFolder',
    required: false,
    label: 'Develop Folder',
    align: 'left',
    field: 'DevelopFolder',
    format: (val: any) => `${val}`,
    sortable: true,
  },
  {
    name: 'RunnerFolder',
    required: false,
    label: 'Runner Folder',
    align: 'left',
    field: 'RunnerFolder',
    format: (val: any) => `${val}`,
    sortable: true,
  },
  {
    name: 'Status',
    required: false,
    label: 'Status',
    align: 'left',
    field: 'Status',
    format: (val: any) => `${val}`,
    sortable: true,
  },
]
const testEnvColumns = [
  {
    name: 'no',
    required: true,
    label: 'No',
    align: 'left',
    field: 'rowIndex',
    sortable: false,
    style: 'max-width: 40px',
    headerStyle: 'max-width: 40px',
  },
  {
    name: 'category',
    required: true,
    label: 'Category',
    align: 'left',
    field: 'Category',
    format: (val: any) => `${val}`,
    sortable: false,
  },
  {
    name: 'name',
    align: 'left',
    label: 'Name',
    field: 'Name',
    sortable: false,
    style: 'min-width: 100px',
    headerStyle: 'min-width: 100px',
  },
  {
    name: 'value',
    align: 'left',
    label: 'Value',
    field: 'Value',
    style: 'max-width: 100px',
    headerStyle: 'max-width: 100px',
    sortable: false,
    classes: 'ellipsis',
  },
  {
    name: 'description',
    align: 'left',
    label: 'Description',
    field: 'Description',
    sortable: false,
  },
  {
    name: 'use',
    align: 'left',
    label: '',
    field: 'use',
    sortable: false,
  },
  {
    name: 'delete',
    align: 'left',
    label: '',
    field: 'use',
    sortable: false,
  },
]
export { clientColumns, testEnvColumns }
