export interface RegressionInterface {
    Id: string,
    Name: string,
    Release: string,
    Build: string,
    IsOfficial: boolean,
    CreatedDate: Date,
    Description: string,
    CreateBy: string,
    StartDate: Date,
    EndDate: Date,
    RegressionTestIds: string[],
    PassRate: string,
    Total: number,
    Passed: number,
    Failed: number,
    AnalysedPass: number,
    AnalysedFail: number,
    Incompatible: number,
}
